version: "3.3"

services:
    backend-api:
        image: us.gcr.io/cs-5346-apartmentwebsite/backend-api:1
        # build:
        #   dockerfile: Dockerfile
        #   context: ./backend
        command: bash -c "npm install && npm run dev"
        volumes:
          - /app/node_modules
          - ./backend:/app
        ports:
          - 8000:8000
        networks:
          - apartments-net

    frontend-app:
        tty: true
        image: us.gcr.io/cs-5346-apartmentwebsite/frontend-app:1
        # build:
        #   dockerfile: Dockerfile
        #   context: ./frontend
        command: bash -c "npm install --silent && npm rebuild node-sass --force && npm start"
        volumes:
          - /app/node_modules
          - ./frontend:/app
        restart: always
        depends_on:
          - backend-api
        ports:
          - 3000:3000
        networks:
          - apartments-net
        labels:
          kompose.service.type: LoadBalancer

# we are using a network to connect these
# two containers. They will be part of the same virtual network
# called 'backend'.
networks:
    apartments-net:
