name: Default

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: 
      
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v8'
      with:
        credentials_json: 
        
    - name: 'Set up SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      
    - name: 'Submit to Cloud Build'
      run: |
        cd frontend
        gcloud builds submit --tag $IMAGE_NAME
        
    - name: 'Deploy to Cloud Run'
      run: gcloud run deploy ${{ secrets.frontend }} --image $IMAGE_NAME -- region us-central1 --platform managed --allow-unathenticated
            
