name: Build Frontend Dev Service

on:
  push:
    branches:
    - 'dev-test'
    paths:
    - 'frontend-dev/**'
    
  

jobs:
  demo-parallelism:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Nothing meaninful'
      run: 'echo Silly V'
      
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
       
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      
    - name: 'Submit to cloud build'
      run: |
        cd frontend-dev
        gcloud builds submit --tag us.gcr.io/cs-5346-apartmentwebsite/frontend-dev
        
    - name: 'Deploy to Cloud Run'
      run: gcloud run deploy frontend-dev --image=us.gcr.io/cs-5346-apartmentwebsite/frontend-dev:latest --region=us-central1 --min-instances=1 --allow-unauthenticated --port=3001 --memory=1Gi

